client_profile/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
# from .views import PromoPlanCreateView, PromoPlanUpdateView, promo_plan_list

app_name= 'client_profile'

urlpatterns = [
    path('', views.profile_view, name='profile_view'),
    path('edit', views.profile_edit, name='profile_edit'),
    path('products/', views.profile_products, name='profile_products'),
    path('products/create/', views.product_create, name='product_create'),
    # # path('products/edit/<int:product_id>/', views.product_edit, name='product_edit'),
    # path('product/<int:id>/edit/', views.product_edit, name='product_edit'),

    # path('products/create/', views.product_create_or_edit, name='product_create'),
    # path('products/edit/<int:id>/', views.product_edit, name='product_edit'),
    # path('products/detail/<int:id>/', views.product_detail, name='product_detail'),

    # path('products/form/', views.product_form, name='product_form'),
    # path('add_account/', views.product_form, name='add_account'),
    # path('remove_account/', views.product_form, name='remove_account'),
    path('promo-plans/', views.promo_plan_list, name='promo_plan_list'),
    # path('promo-plan/create/', PromoPlanCreateView.as_view(), name='create_promo_plan'),
    # path('promo-plan/<int:pk>/edit/', PromoPlanUpdateView.as_view(), name='edit_promo_plan'),
    path('promo-plan/create/', views.create_or_edit_promo_plan, name='create_promo_plan'),
    path('promo-plan/<int:pk>/edit/', views.create_or_edit_promo_plan, name='edit_promo_plan'),
    path('promo-plan/<int:pk>/remove/', views.remove_promo_plan, name='remove_promo_plan'),  # Add this line


]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('',views.send_message , name='contact'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('admin_soft.urls')),
    path('admin/', admin.site.urls),
    path('scrapper/', include('scrapper.urls', namespace='scrapper')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('client_profile/', include('client_profile.urls',namespace='client_profile')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('dashboard/', include('dashboard.urls')),


]


urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

client_profile/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Profile, Product, ProductAccountLinkId, Photo,Account_id, PromoPlan #, Keyword, ProductKeyword, Account, ProductAccountLink
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields= ['username','first_name','last_name','email'] 

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['client','plan']
        
class ProductAccountIdLinkForm(forms.ModelForm):
    account = forms.ModelChoiceField(queryset=Account_id.objects.all(), required=True)

    class Meta:
        model = ProductAccountLinkId
        fields = ['account', 'identifier']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['account'].label = 'Account (required)'
        self.fields['identifier'].label = 'Identifier (required)'

    def clean(self):
        cleaned_data = super().clean()
        # Ensure account is selected
        if not cleaned_data.get('account'):
            self.add_error('account', 'Account is required')
        # Ensure identifier is provided
        if not cleaned_data.get('identifier'):
            self.add_error('identifier', 'Identifier is required')
        return cleaned_data

ProductAccountIdLinkFormSet = inlineformset_factory(
    Product,
    ProductAccountLinkId,
    form=ProductAccountIdLinkForm,
    extra=1,
    can_delete=True
)

# class ProductAccountLinkForm(forms.ModelForm):
#     account = forms.ModelChoiceField(queryset=Account.objects.all(), required=True)

#     class Meta:
#         model = ProductAccountLink
#         fields = ['account', 'url']

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['account'].label = 'Account (required)'

#     def clean(self):
#         cleaned_data = super().clean()
#         if not cleaned_data.get('account'):
#             self.add_error('account', 'Account is required')
#         return cleaned_data

# ProductAccountLinkFormSet = inlineformset_factory(
#     Product,
#     ProductAccountLink,
#     form=ProductAccountLinkForm,
#     extra=1,
#     can_delete=True
# )

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image']

PhotoFormSet = inlineformset_factory(Product, Photo, form=PhotoForm, extra=1, can_delete=True)

# class KeywordForm(forms.Form):
#     keyword = forms.CharField(max_length=100)

# class ProductKeywordForm(forms.ModelForm):
#     keyword = forms.CharField(max_length=100)

#     class Meta:
#         model = ProductKeyword
#         fields = ['keyword']

#     def save(self, commit=True):
#         # Get or create the Keyword instance
#         keyword, created = Keyword.objects.get_or_create(name=self.cleaned_data['keyword'])
#         # Associate the keyword with the ProductKeyword instance
#         self.instance.keyword = keyword
#         if commit:
#             self.instance.save()
#         return self.instance

# ProductKeywordFormSet = inlineformset_factory(
#     Product,
#     ProductKeyword,
#     form=ProductKeywordForm,
#     extra=1,
#     can_delete=True
# )

# Promo manager
class PromoPlanForm(forms.ModelForm):
    class Meta:
        model = PromoPlan
        fields = ['product', 'start_date', 'end_date', 'discount_percentage']
        widgets = {
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'id': 'id_start_date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'id': 'id_end_date'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(PromoPlanForm, self).__init__(*args, **kwargs)
        if user:
            # Filter products by the user's profile
            self.fields['product'].queryset = Product.objects.filter(profile=user.profile)



class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['TITLE', 'description', 'RSP', 'RSP_VAT', 'category', 'subcategory', 'brand']

client_profile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import UserForm, ProfileForm, ProductForm, PhotoFormSet, ProductAccountIdLinkFormSet, PromoPlanForm # , ProductKeywordFormSet, KeywordForm, ProductAccountLinkFormSet
from .models import Profile, Product, PromoPlan #, Keyword
from django.urls import reverse
# from django.core.exceptions import ValidationError
from django.contrib import messages

@login_required
def profile_view(request):
    profile = Profile.objects.get(user=request.user)
    products = profile.products.all()
    return render(request, 'client_profile/profile.html', {
        'profile': profile, 
        'user': request.user,  
        'products': products,
        'segment': 'client_profile'
    })

@login_required
def product_detail(request, id):
    product = get_object_or_404(Product, id=id, profile=request.user.profile)
    return render(request, 'client_profile/product_detail.html', {'product': product})

# @login_required
# def product_create(request):
#     if request.method == 'POST':
#         product_form = ProductForm(request.POST)
#         account_link_formset = ProductAccountLinkFormSet(request.POST, prefix='accounts')
#         photo_formset = PhotoFormSet(request.POST, request.FILES, prefix='photos')

#         if all([product_form.is_valid(), account_link_formset.is_valid(), photo_formset.is_valid()]):
#             product = product_form.save(commit=False)
#             product.profile = request.user.profile
#             product.save()

        

#             # Handle account links
#             for form in account_link_formset.save(commit=False):
#                 form.product = product
#                 form.save()
#             account_link_formset.save_m2m()

#             # Handle photos
#             for form in photo_formset.save(commit=False):
#                 form.product = product
#                 form.save()
#             photo_formset.save_m2m()

#             return redirect('client_profile:profile_products')
#     else:
#         product_form = ProductForm()
#         account_link_formset = ProductAccountLinkFormSet(prefix='accounts')
#         photo_formset = PhotoFormSet(prefix='photos')

#     return render(request, 'client_profile/product_create.html', {
#         'product_form': product_form,
#         'account_link_formset': account_link_formset,
#         'photo_formset': photo_formset,
#         'segment': 'product_create',
#     })
@login_required
def product_create(request):
    if request.method == 'POST':
        product_form = ProductForm(request.POST)
        # account_link_formset = ProductAccountLinkFormSet(request.POST, prefix='accounts')
        account_id_link_formset = ProductAccountIdLinkFormSet(request.POST, prefix='account_ids')  # New formset
        photo_formset = PhotoFormSet(request.POST, request.FILES, prefix='photos')

        # if all([product_form.is_valid(), account_link_formset.is_valid(), account_id_link_formset.is_valid(), photo_formset.is_valid()]):  # Updated validation
        if all([product_form.is_valid(), account_id_link_formset.is_valid(), photo_formset.is_valid()]):  # Updated validation
            product = product_form.save(commit=False)
            product.profile = request.user.profile
            product.save()

            # Handle account links
            # for form in account_link_formset.save(commit=False):
            #     form.product = product
            #     form.save()
            # account_link_formset.save_m2m()

            # Handle account id links (New block)
            for form in account_id_link_formset.save(commit=False):
                form.product = product
                form.save()
            account_id_link_formset.save_m2m()

            # Handle photos
            for form in photo_formset.save(commit=False):
                form.product = product
                form.save()
            photo_formset.save_m2m()

            return redirect('client_profile:profile_products')
    else:
        product_form = ProductForm()
        # account_link_formset = ProductAccountLinkFormSet(prefix='accounts')
        account_id_link_formset = ProductAccountIdLinkFormSet(prefix='account_ids')  # New formset
        photo_formset = PhotoFormSet(prefix='photos')

    return render(request, 'client_profile/product_create.html', {
        'product_form': product_form,
        # 'account_link_formset': account_link_formset,
        'account_id_link_formset': account_id_link_formset,  # Pass the new formset to the template
        'photo_formset': photo_formset,
        'segment': 'product_create',
    })


# @login_required
# def product_edit(request, id):
#     product = get_object_or_404(Product, id=id, profile=request.user.profile)

#     if request.method == 'POST':
#         product_form = ProductForm(request.POST, instance=product)
#         account_link_formset = ProductAccountLinkFormSet(request.POST, instance=product)
#         photo_formset = PhotoFormSet(request.POST, request.FILES, instance=product)

#         if product_form.is_valid() and account_link_formset.is_valid() and photo_formset.is_valid():
#             try:
#                 product = product_form.save(commit=False)
#                 product.save()

#                 # Handle account links
#                 for account_link in account_link_formset.save(commit=False):
#                     if 'remove-account-0' in request.POST:
#                         account_link.delete()
#                     else:
#                         account_link.product = product
#                         account_link.save()
#                 account_link_formset.save_m2m()

#                 # Handle photos
#                 for photo in photo_formset.save(commit=False):
#                     if 'remove-photo-0' in request.POST:
#                         photo.delete()
#                     else:
#                         photo.product = product
#                         photo.save()
#                 photo_formset.save_m2m()

#                 return redirect('client_profile:profile_products')
#             except Exception as e:
#                 print(e)
#                 return render(request, 'client_profile/product_edit.html', {
#                     'product': product,
#                     'product_form': product_form,
#                     'account_link_formset': account_link_formset,
#                     'photo_formset': photo_formset,
#                 })
#     else:
#         product_form = ProductForm(instance=product)
#         account_link_formset = ProductAccountLinkFormSet(instance=product)
#         photo_formset = PhotoFormSet(instance=product)

#     return render(request, 'client_profile/product_edit.html', {
#         'product': product,
#         'product_form': product_form,
#         'account_link_formset': account_link_formset,
#         'photo_formset': photo_formset,
#     })


# @login_required
# def product_edit(request, id):
#     product = get_object_or_404(Product, id=id, profile=request.user.profile)

#     if request.method == 'POST':
#         product_form = ProductForm(request.POST, instance=product)
#         account_link_formset = ProductAccountLinkFormSet(request.POST, instance=product)
#         photo_formset = PhotoFormSet(request.POST, request.FILES, instance=product)

#         if product_form.is_valid() and account_link_formset.is_valid() and photo_formset.is_valid():
#             try:
#                 product = product_form.save()

#                 # Handle account links
#                 for account_link in account_link_formset.save(commit=False):
#                     if 'remove-account-0' in request.POST:
#                         account_link.delete()
#                     else:
#                         account_link.product = product
#                         account_link.save()
#                 account_link_formset.save_m2m()

#                 # Handle photos
#                 for photo in photo_formset.save(commit=False):
#                     if 'remove-photo-0' in request.POST:
#                         photo.delete()
#                     else:
#                         photo.product = product
#                         photo.save()
#                 photo_formset.save_m2m()


#                 # Handle keywords using formset
#                 keyword_formset = ProductKeywordFormSet(request.POST, instance=product)
#                 for form in keyword_formset:
#                     if form.is_valid():
#                         form.instance.save()  # Directly save each valid keyword instance

#                 return redirect('client_profile:profile_products')
#             except Exception as e:
#                 print(e)
#                 return render(request, 'client_profile/product_edit.html', {
#                     'product': product,
#                     'product_form': product_form,
#                     'account_link_formset': account_link_formset,
#                     'photo_formset': photo_formset,
#                 })
#     else:
#         product_form = ProductForm(instance=product)
#         account_link_formset = ProductKeywordFormSet(instance=product)
#         photo_formset = PhotoFormSet(instance=product)

#     return render(request, 'client_profile/product_edit.html', {
#         'product': product,
#         'product_form': product_form,
#         'account_link_formset': account_link_formset,
#         'photo_formset': photo_formset,
#     })



@login_required
def profile_products(request):
    profile = Profile.objects.get(user=request.user)
    products = profile.products.all()
    context = {
        'profile': profile,
        'products': products,
        'segment': 'profile_products'
    }
    return render(request, 'client_profile/profile_products.html', context)


@login_required
def profile_edit(request):
    profile = Profile.objects.get(user=request.user)

client_profile/templates/client_profile/product_detail.html
{% extends 'layouts/base.html' %}

{% block content %}
  <h1>Product Detail</h1>

  <div class="row">
    <div class="col-md-6">
      <h2>Product Information</h2>
      <table class="table table-striped">
        <tr>
          <th>Title:</th>
          <td>{{ product.TITLE }}</td>
        </tr>
        <tr>
          <th>ASIN:</th>
          <td>{{ product.ASIN }}</td>
        </tr>
        <tr>
          <th>Description:</th>
          <td>{{ product.description }}</td>
        </tr>
      </table>
    </div>

    <div class="col-md-6">
      <h2>Accounts</h2>
      <table class="table table-striped">
        <tr>
          <th>Account</th>
          <th>URL</th>
        </tr>
        {% for account in product.accounts.all %}
          <tr>
            <td>{{ account.account }}</td>
            <td>{{ account.url }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <h2>Photos</h2>
      <div class="photo-gallery">
        {% for photo in product.photos.all %}
          <div class="photo">
            <img src="{{ photo.image.url }}" alt="Photo">
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

client_profile/templates/client_profile/profile.html
{% extends 'layouts/base.html' %}

{% block content %}






<div class="container-fluid">
    <div class="row mt-5">
        <div class="row">
            <h3>My Profile</h3>
        </div>
        <div class="row">
            <div class="card mb-4">
            <div class="card-body">
            <div class="row">
            <div class="col-sm-3">
            <p class="mb-0">User Name</p>
            </div>
            <div class="col-sm-9">
            <p class="text-muted mb-0 font-weight-bolder">{{profile.user}}</p>
            </div>
            </div>
            <hr>
            <div class="row">
            <div class="col-sm-3">
            <p class="mb-0">Email</p>
            </div>
            <div class="col-sm-9">
            <p class="text-muted mb-0 font-weight-bolder">{{profile.user.email}}</p>
            </div>
            </div>
            <hr>
            <div class="row">
            <div class="col-sm-3">
            <p class="mb-0">Client</p>
            </div>
            <div class="col-sm-9">
            <p class="text-muted mb-0 font-weight-bolder">{{profile.client}}</p>
            </div>
            </div>
            <hr>
            <div class="row">
            <div class="col-sm-3">
            <p class="mb-0">My plan</p>
            </div>
            <div class="col-sm-9">
            <p class="text-muted mb-0 font-weight-bolder">{{profile.plan}}</p>
            </div>
            </div>
            <hr>
            <div class="row">
            <div class="col-sm-3">
            <p class="mb-0">Address</p>
            </div>
            <div class="col-sm-9">
            <p class="text-muted mb-0">Bay Area, San Francisco, CA</p>
            </div>
            </div>
            </div>
            </div>
            <div class="p-5">
            <a class="btn btn-outline-primary" href="{% url 'client_profile:profile_edit' %}"> Edit Profile</a>
            </div>
        </div>
    </div>


{% endblock content %}

client_profile/templates/client_profile/profile_products.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">


<div class="row my-4">
    <div class="col-lg-12 col-md-12">
      <div class="card">
        <div class="card-header pb-0">
          <div class="row">
            <div class="col-lg-6 col-7">
              <h6>My products</h6>
              <p class="text-sm mb-0">
                <span class="font-weight-bold ms-1">{{ products.count }} </span> products in my radar list
              </p>
            </div>

          </div>
        </div>
        <div class="card-body px-0 pb-2">
          <div class="table-responsive">
            <table class="table align-items-center mb-0">
              <thead>
                <tr>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Title</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Category</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Subcategory</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Images</th>
                  <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">RSV|RSV+VAT</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Edit</th>
                  <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Detail</th>
                </tr>
              </thead>
              <tbody>
                {% for product in products %}

                <tr>
                  <td>
                    <div class="d-flex px-2 py-1">

                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{product.TITLE}}</h6>
                      </div>
                    </div>
                  </td>

                  <td>
                    <div class="d-flex px-2 py-1">

                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{product.category}}</h6>
                      </div>
                    </div>
                  </td>


                  <td>
                    <div class="d-flex px-2 py-1">

                      <div class="d-flex flex-column justify-content-center">
                        <h6 class="mb-0 text-sm">{{product.subcategory}}</h6>
                      </div>
                    </div>
                  </td>

                  <td>

                    <div class="avatar-group mt-2">
                        {% for photo in product.photos.all %}
                            <a href="javascript:;" class="avatar avatar-xs rounded-circle" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{{ photo.image_description }}">
                                <img src="{{ photo.image.url }}" alt="photo">
                            </a>
                        {% endfor %}
                    </div>
                

                  </td>
                  <td >
                    <span class="text-xs font-weight-bold"> {{product.RSP}}</span>
                    <br>
                    <span class="text-xs">{{ product.RSP_VAT }}</span>
        
                  </td>
                  <td class="align-middle text-center text-sm">
                    <div >

                      <div class="d-flex flex-column justify-content-center">
                        <a href="#">Edit</a>

                      </div>
                    </div>
                  </td>
                  <td class="align-middle text-center text-sm">
                    <div >

                      <div class="d-flex flex-column justify-content-center">
                        <a href="#">details</a>

                      </div>
                    </div>
                  </td>
                </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

  </div>

    <a href="{% url 'client_profile:product_create' %}"class="btn btn-primary">Add New Product</a>

</div>

{% endblock content %}

client_profile/templates/client_profile/promo_plan_form.html
{% extends 'layouts/base.html' %}

{% block content %}

<div class="container-fluid">
    <div class="row mt-4">
        <div class="card">
            <h1 class="mt-3">{% if form.instance.pk %}Edit{% else %}Create{% endif %} Promo Plan</h1>
            <br>
            <form method="post" action="{% if form.instance.pk %}{% url 'client_profile:edit_promo_plan' form.instance.pk %}{% else %}{% url 'client_profile:create_promo_plan' %}{% endif %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">{% if form.instance.pk %}Update{% else %}Create{% endif %}</button>
            </form>
        </div>
    </div>
</div>   


{% endblock %}

client_profile/templates/client_profile/promo_plan_list.html
<!-- Example: client_profile/promo_plan_list.html -->
{% extends 'layouts/base.html' %}

{% block content %}

<div class="container-fluid">
    
    <div class="row my-4">
      <br>
      <h2 class="mt-4">Promo Plans Manager</h2>


    </div>
    <a href="{% url 'client_profile:create_promo_plan' %}" class="btn btn-primary">Launch Promo Plan</a>

    {% if promo_plans %}
    
    <div class="row mt-3"></div>
        <div class="col-lg-12 col-md-12">
          <div class="card">
            <div class="card-header pb-0">
              <div class="row">
                <div class="col-lg-6 col-7">
                  <h6>My Plans List</h6>
    
                </div>
    
              </div>
            </div>
            <div class="card-body px-0 pb-2">
              <div class="table-responsive">
                <table class="table align-items-center mb-0">
                  <thead>
                    <tr>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Product</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Start Date</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">End Date</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Desired Price</th>
                      <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2">Duration (days)</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Edit plan</th>
                      <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Remove plan</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for promo_plan in promo_plans %}
    
                    <tr>
                      <td>
                        <div class="d-flex px-2 py-1">
    
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{promo_plan.product.TITLE}}</h6>
                          </div>
                        </div>
                      </td>
    
                      <td>
                        <div class="d-flex px-2 py-1">
    
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{promo_plan.start_date}}</h6>
                          </div>
                        </div>
                      </td>
    
    
                      <td>
                        <div class="d-flex px-2 py-1">
    
                          <div class="d-flex flex-column justify-content-center">
                            <h6 class="mb-0 text-sm">{{promo_plan.end_date}}</h6>
                          </div>
                        </div>
                      </td>
    
                      <td>
                        <div class="d-flex px-2 py-1">
    
                          <div class="d-flex flex-column justify-content-center">
                            <h4 class="mb-0 text-sm">{{promo_plan.desired_price|floatformat:2}}</h4>
                          </div>
                        </div>
                      </td>
    
    
                      <td>
                        <div class="d-flex px-2 py-1">
    
                          <div class="d-flex flex-column justify-content-center">
                            <h4 class="mb-0 text-sm">{{promo_plan.duration}}</h4>
                          </div>
                        </div>
                      </td>
    
    
                      <td class="align-middle text-center text-sm">
                        <div >
    
                          <div class="d-flex flex-column justify-content-center">
                            <a href="{% url 'client_profile:edit_promo_plan' promo_plan.pk %}">Edit</a>
    
                          </div>
                        </div>
                      </td>
                      <td class="align-middle text-center text-sm">
                        <div >
    
                          <div class="d-flex flex-column justify-content-center">
                            <a href="{% url 'client_profile:remove_promo_plan' promo_plan.pk %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this promo plan?');">Remove</a>
    
                          </div>
                        </div>
                      </td>
                    </tr>
                    {% endfor %}
    
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
    
      </div>
    
      {% else %}
      <p>No promo plans available.</p>
      <a href="{% url 'client_profile:create_promo_plan' %}" class="btn btn-primary">Launch Promo Plan</a>
      {% endif %}
    
    
</div>

{% endblock %}




<!-- <h2>Promo Plans</h2>


<a href="{% url 'client_profile:create_promo_plan' %}" class="btn btn-primary">Launch Promo Plan</a>

{% if promo_plans %}
<table class="table">
    <thead>
        <tr>
            <th>Product</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Desired Price</th>
            <th>Duration (days)</th>
            <th>Edit plan</th>
            <th>Remove plan</th>
        </tr>
    </thead>
    <tbody>
        {% for promo_plan in promo_plans %}
        <tr>
            <td>{{ promo_plan.product }}</td>
            <td>{{ promo_plan.start_date }}</td>
            <td>{{ promo_plan.end_date }}</td>
            <td>{{ promo_plan.desired_price }}</td>
            <td>{{ promo_plan.duration }}</td>
            <td>
              <a href="{% url 'client_profile:edit_promo_plan' promo_plan.pk %}">Edit</a>
          </td>           
           <td>
            <a href="{% url 'client_profile:remove_promo_plan' promo_plan.pk %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this promo plan?');">Remove</a>
          </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No promo plans available.</p>
<a href="{% url 'client_profile:create_promo_plan' %}" class="btn btn-primary">Launch Promo Plan</a>
{% endif %} -->