contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('',views.send_message , name='contact'),

]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard_view', views.dashboard_view, name='dashboard_view'),
    # path('price_view', views.price_view, name='price_view'),
    path('current_price', views.price, name='price'),
    path('Download_data/', views.performance_view, name='performance_view'),
    path('toggle_pin_table/<str:table_name>/', views.toggle_pin_table, name='toggle_pin_table'),
    path('current_price/', views.scrape_user_products_view, name='trigger_scrape_for_user_products'),
    path('download-performance-data/', views.download_performance_data, name='download_performance_data'),


    # path('', views.dashboard_view, name='dashboard'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('admin_soft.urls')),
    path('admin/', admin.site.urls),
    path('scrapper/', include('scrapper.urls', namespace='scrapper')),
    path('contact/', include('contact.urls',namespace='contact')),
    path('client_profile/', include('client_profile.urls',namespace='client_profile')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('dashboard/', include('dashboard.urls')),


]


urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

dashboard/models.py
# # dashboard/models.py
# from django.db import models
# from django.utils import timezone
# from scrapper.models import ScrapedData

# class PerformanceData(models.Model):
#     scraped_data = models.ForeignKey(ScrapedData, on_delete=models.CASCADE, related_name='performance_data')
#     product = models.CharField(max_length=100)
#     pds = models.FloatField(default=0)
#     pcs = models.FloatField(default=0)
#     opps = models.FloatField(default=0)
#     scraped_at = models.DateTimeField(default=timezone.now)
#     amazon_sold_by = models.CharField(max_length=20, blank=True, null=True)
#     compliance_flags = models.JSONField(default=dict)
#     user_accounts = models.JSONField(default=list)
#     on_promo = models.BooleanField(default=False)
#     my_price = models.FloatField(default=0)

#     def __str__(self):
#         return f"Performance Data for {self.product} at {self.scraped_at}"

dashboard/forms.py
from django import forms
from client_profile.models import Category, Subcategory, Brand, Product

class FilterForm(forms.Form):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        required=False,
        widget=forms.Select  # Dropdown for Category
    )
    subcategory = forms.ModelChoiceField(
        queryset=Subcategory.objects.all(),
        required=False,
        widget=forms.Select  # Dropdown for Subcategory
    )
    brand = forms.ModelChoiceField(
        queryset=Brand.objects.all(),
        required=False,
        widget=forms.Select  # Dropdown for Brand
    )
    product = forms.ModelChoiceField(
        queryset=Product.objects.all(),
        required=False,
        widget=forms.Select  # Dropdown for Product
    )

# from django import forms
# from client_profile.models import Product

# TIME_PERIOD_CHOICES = [
#     ('1_day', '1 Day'),
#     ('1_week', '1 Week'),
#     ('1_month', '1 Month'),
#     ('3_months', '3 Months'),
#     ('6_months', '6 Months'),
#     ('1_year', '1 Year'),
# ]

# class TimePeriodForm(forms.Form):
#     product = forms.ModelChoiceField(queryset=Product.objects.none())
#     time_period = forms.ChoiceField(choices=TIME_PERIOD_CHOICES)

#     def __init__(self, *args, **kwargs):
#         profile = kwargs.pop('profile')
#         super().__init__(*args, **kwargs)
#         self.fields['product'].queryset = Product.objects.filter(profile=profile)

dashboard/views.py
from django.shortcuts import render, redirect
from scrapper.models import ScrapedData, ScrapedBulkData
from client_profile.models import Profile, PinnedTable, Brand ,Product, Subcategory, PromoPlan
# from django.db.models import OuterRef, Subquery, Max, F, Value as V, FloatField
from django.db.models import OuterRef, Max, Subquery
from django.contrib.auth.decorators import login_required
# from django.db.models.functions import Coalesce
from .dash_apps.app import plot_dashboard
import pandas as pd
from scrapper.tasks import scrape_user_products_task ,scrape_user_Bulk_product_task
# from dashboard.tasks import cache_user_data, refresh_materialized_views

from dashboard.tasks import refresh_materialized_views
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from io import BytesIO
import logging
from dashboard.utils import get_materialized_view_data  # process_data, get_cached_data
import json
from django.core.cache import cache

# Initialize logger
logger = logging.getLogger(__name__)


@login_required
def scrape_user_products_view(request):
    try:
        # Get the current user's profile
        profile = Profile.objects.get(user=request.user)
        user_products = Product.objects.filter(profile=profile)

        # Extract product IDs to pass to the Celery tasks
        product_ids = list(user_products.values_list('id', flat=True))

        # Trigger the Celery tasks
        print('Scraping products for user...')
        scrape_user_products_task.delay(product_ids)
        
        print('Scraping bulk products for user...')
        scrape_user_Bulk_product_task.delay(product_ids)

        print('Refresh materialized view')
        refresh_materialized_views.delay()

        # print('Caching data for user...')
        # cache_user_data.delay(request.user.id)



        # Notify the user
        messages.success(request, "Updating the table is in progress. Please check back in a few minutes.")
    except Exception as e:
        print(f"Error in scrape_user_products_view: {e}")
        messages.error(request, "An error occurred during data scraping and caching. Please try again.")

    return redirect('dashboard:price')


@login_required
def dashboard_view(request):
    try:
        # Get user profile and account names
        profile = Profile.objects.get(user=request.user)
        account_names = list(
            profile.products.values_list('accounts_id__name', flat=True).distinct().exclude(accounts_id__name__isnull=True)
        )
        
        # Default to last week data initially
        initial_period = "last_week"
        df = get_materialized_view_data(initial_period)
        
        # Pass data to Plotly Dash
        plot_dashboard(df, account_names)
        context = {
            'segment': 'dashboard_view',

        }
        return render(request, 'dashboard/dashboard.html', context)


    except Exception as e:
        print(f"Error in dashboard_view: {e}")
        return JsonResponse({'error': str(e)}, status=500)


# @login_required
# def dashboard_view(request):
#     try:
#         # Use caching
#         cache_key = f'dashboard_data_{request.user.id}'
#         cached_data = cache.get(cache_key)

#         if not cached_data:
#             return JsonResponse(
#                 {"error": "Am error occour please try again later, we are working on it."},
#                 status=400
#             )

#         # Pass cached data directly to Plotly Dash
#         profile = Profile.objects.get(user=request.user)
#         account_names = list(
#             profile.products.values_list('accounts_id__name', flat=True).distinct().exclude(accounts_id__name__isnull=True)
#         )
#         plot_dashboard(cached_data, account_names)
#         context = {
#             'segment': 'dashboard_view',

#         }
#         return render(request, 'dashboard/dashboard.html', context)


#     except Exception as e:
#         print(f"Error in dashboard_view: {e}")
#         return JsonResponse({'error': str(e)}, status=500)


@login_required
def performance_view(request):
    try:
        context = {
            'segment': 'scraped_data',
        }

        return render(request, 'dashboard/product_performance.html', context)

    except Exception as e:
        print(f"An error occurred in performance_view: {e}")
        return render(request, 'dashboard/product_performance.html', {
            'error_message': 'An error occurred while retrieving the data.'
        })


@login_required
def price(request):
    try:
        profile = Profile.objects.get(user=request.user)  # Assuming you have a user profile
        pinned_tables = profile.pinned_tables.all()


        # Get selected product IDs and selected columns from the request
        selected_product_ids = request.GET.getlist('products')
        selected_columns = request.GET.getlist('columns')

        # Filter products for the dropdown
        all_products = profile.products.all()
        filtered_products = all_products
        if selected_product_ids:
            filtered_products = filtered_products.filter(id__in=selected_product_ids)

        # Define dynamic columns based on user's accounts
        user_accounts = profile.products.values_list('accounts_id__name', flat=True).distinct().exclude(accounts_id__name__isnull=True)
        all_columns = []
        for account in user_accounts:
            account_lower = account.lower()
            all_columns.extend([
                {'name': f'{account_lower}_price', 'header': f'{account} Price'},
                {'name': f'{account_lower}_compliance_flag', 'header': f'{account} Compliance'},
                {'name': f'{account_lower}_discount', 'header': f'{account} Discount'},
            ])

        all_columns.extend([
                        {'name': 'promo_flag', 'header': 'Promo Flag'},
                        {'name': 'RSP', 'header': 'RSP'},
                        {'name': 'final_price', 'header': 'Reference Price'},
                        {'name': 'amazon_sold_by', 'header': 'Amazon KSA Sold By'},
                        {'name': 'noon_sa_sold_by', 'header': 'Noon KSA Sold By'},
                        {'name': 'opps', 'header': 'Online Price Performance Score'},
                        {'name': 'price_deviation_score', 'header': 'Price Deviation Score'},
                        {'name': 'account_deviation_score', 'header': 'Accunts Deviation Score'},
                    ])
        # Filter columns based on selected_columns
        if selected_columns:
            columns = [col for col in all_columns if col['name'] in selected_columns]
        else:
            # Default to show all columns if none selected
            columns = all_columns



        # Rest of your view logic continues here...
        # Subquery to find the maximum scraped_at date for each product
        max_date_subquery = ScrapedData.objects.filter(
            product=OuterRef('product')
        ).order_by('-scraped_at').values('scraped_at')[:1]

        # Get all scraped data where scraped_at is the max date for each product (fetch model instances)
        max_scraped_data = ScrapedData.objects.filter(
            scraped_at=Subquery(max_date_subquery),
            product__in=filtered_products.filter(is_competitor=False)  # Ensure only non-competitor products
        ).select_related('product')


        # Get user accounts and filter out None values
        user_accounts = profile.products.values_list('accounts_id__name', flat=True).distinct().exclude(accounts_id__name__isnull=True)

        # Check if "amazon" is in the user's accounts
        show_amazon_sold_by = 'amazon' in user_accounts

        # Check if the current table is pinned by the user
        is_table_pinned = profile.pinned_tables.filter(table_name="CurrentPriceStatus").exists()

        # Find the maximum `scraped_at` date across all products
        latest_scraped_date = max_scraped_data.aggregate(latest_date=Max('scraped_at'))['latest_date']

        context = {
            'max_scraped_data': max_scraped_data,
            'latest_scraped_date': latest_scraped_date,
            'is_table_pinned': is_table_pinned,
            'segment': 'price',
            'user_accounts': user_accounts,
            'show_amazon_sold_by': show_amazon_sold_by,
            'columns': columns,
            'pinned_tables': pinned_tables,
            'selected_product_ids': selected_product_ids,
            'selected_columns': selected_columns,
            'all_products': all_products,  # Provide the list of all products
            'all_columns': all_columns,    # Provide the column data for the template
        }

        return render(request, 'dashboard/price.html', context)

    except Exception as e:
        print(f"An error occurred in price: {e}")
        return render(request, 'dashboard/price.html', {
            'error_message': 'An error occurred while retrieving the data.'
        })


@login_required
def download_performance_data(request):
    try:
        # Retrieve cached data
        cache_key = f'dashboard_data_{request.user.id}'
        cached_data = cache.get(cache_key)

        if not cached_data:
            return HttpResponse("Data is not yet cached. Please try again later.", status=400)

        # Deserialize cached data
        data = json.loads(cached_data)

        # Process data for Excel sheets
        scraped_data_df = pd.DataFrame([{
            'Scraped At': data['scraped_at'][i],
            'RSP VAT': data['RSP_VAT'][i],
            'Discount %': data['discount_percentage'][i],
            'Amazon Price': data['amazon_price'][i],
            'Nahdi Price': data['nahdi_price'][i],
            'Dawa Price': data['dawa_price'][i],
            'Noon_sa Price': data['noon_sa_price'][i],
            'Amazon Discount': data['amazon_discount'][i],
            'Nahdi Discount': data['nahdi_discount'][i],
            'Dawa Discount': data['dawa_discount'][i],

dashboard/templates/dashboard/dash_app.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %} 
<!-- <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h1>Dashboard</h1>
    {% load plotly_dash %}  
    <div id="dash-container">
        {% plotly_app "app" %}
    </div>
</body> -->
{% endblock content %}

dashboard/templates/dashboard/dashboard.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load plotly_dash %}


{% block content %}
   
    <div class="{% plotly_class name='OPPS_Line' %} container-fluid" >
                {% plotly_app name="OPPS_Line" ratio=1.0 %}
    </div>

{% endblock content %}

dashboard/templates/dashboard/price.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %} 

<!-- Slide toggle -->
<!-- <style> 
  /* The switch - the box around the slider */
.switch {
  position: relative;
  display: inline-block;
  width: 60px;
  height: 34px;
}

/* Hide default HTML checkbox */
.switch input {
  opacity: 0;
  width: 0;
  height: 0;
}

/* The slider */
.slider {
  position: absolute;
  cursor: pointer;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: #ccc;
  -webkit-transition: .4s;
  transition: .4s;
}

.slider:before {
  position: absolute;
  content: "";
  height: 26px;
  width: 26px;
  left: 4px;
  bottom: 4px;
  background-color: white;
  -webkit-transition: .4s;
  transition: .4s;
}

input:checked + .slider {
  background-color: #2196F3;
}

input:focus + .slider {
  box-shadow: 0 0 1px #2196F3;
}

input:checked + .slider:before {
  -webkit-transform: translateX(26px);
  -ms-transform: translateX(26px);
  transform: translateX(26px);
}

/* Rounded sliders */
.slider.round {
  border-radius: 34px;
}

.slider.round:before {
  border-radius: 50%;
}
</style> -->
<script>
  // Auto-dismiss alert after 5 seconds (5000 ms)
  document.addEventListener("DOMContentLoaded", function () {
    const alertElement = document.querySelector(".alert-dismissible");
    if (alertElement) {
      setTimeout(() => {
        alertElement.classList.remove("show"); // Remove 'show' class
        alertElement.classList.add("fade");   // Optionally add 'fade' class for transition
        alertElement.style.display = "none";  // Hide the alert
      }, 5000); // 5000 ms = 5 seconds
    }
  });
</script>


<div class="container-fluid py-4">

  {% if messages %}
  <div class="container mt-4">
    {% for message in messages %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}


<div class="row mt-4">
  <h1>Current Price Status </h1>
</div>


<div class="col-12">
  <div class="card">
    <div class="card-header pb-0">
      <div class="row">
        <div class="col-lg-6 col-7">
          <p class="text-sm mb-0">
            The table's last update was on <span style="font-weight: bold;" >{{ latest_scraped_date|date:"F j, Y, g:i a" }}</span>
        </div>
      </div>
    </div>

    <div class="card-body px-0 pb-2">

      <div class="container-fluid">
        <div class="raw">

          <form action="{% url 'dashboard:trigger_scrape_for_user_products' %}" method="post">
            {% csrf_token %}
            <div class="d-grid gap-2">
              <button class="btn btn-primary" type="submit">Update Price Now</button>
            </div>
          </form>
        
        </div>
      </div>
      
      <div class="container-fluid">
        <div class="raw">
      <!-- Product and Column Selection Form -->
      <div class="d-grid gap-2">

      <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
        Filter Prodcuts and columns 
      </button>
      </div>

      <div class="collapse" id="collapseExample">
      
      <form method="get" id="filter-form" class="mb-4">
        <div class="row g-3">
            <!-- Product Dropdown -->
            <div class="col-md-6">
                <label for="products" class="form-label fw-bold">Select Products:</label>
                <select id="products" name="products" class="form-select" multiple>
                    {% for product in all_products %}
                        <option value="{{ product.id }}" {% if product.id|stringformat:"s" in selected_product_ids %}selected{% endif %}>
                            {{ product.TITLE }}
                        </option>
                    {% endfor %}
                </select>
                <small class="text-muted">Hold Ctrl (Windows) or Command (Mac) to select multiple products.</small>
            </div>
      
            <!-- Columns Checkbox Dropdown -->
            <div class="col-md-6">
              <label for="columns">Select Columns to Display:</label><br>
              {% for column in columns %}
                  <input type="checkbox" name="columns" value="{{ column.name }}" id="{{ column.name }}"
                        {% if column.name in selected_columns %}checked{% endif %}>
                  <label for="{{ column.name }}">{{ column.header }}</label><br>
              {% endfor %}
            </div>


            
        </div>
      
        <!-- Submit Button -->
        <div class="mt-4">
            <button type="submit" class="btn btn-success w-100">Apply Filters</button>
        </div>
      </form>
      
      </div>
        
        </div>
      </div>
      
      <div class="card-body px-0 pb-2">
          <div class="table-responsive">
              <!-- Product Table -->
              <table class="table align-items-center mb-0" id="CurrentPriceStatus" class="display">
                <thead>
                    <tr>
                        <th class="text-center">Product</th>
                        {% for column in columns %}
                            <th class="text-center">{{ column.header }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for data in max_scraped_data %}
                        <tr>
                            <td>{{ data.product.TITLE }}</td>
                            {% for column in columns %}
                                <td class="text-center">
                                    {% if "_price" in column.name or "_discount" in column.name %}
                                        {{ data|get_item2:column.name|floatformat:"2"|default_if_none:"N/A" }}
                                    {% elif "_compliance_flag" in column.name %}
                                        {% if data|get_item2:column.name %}
                                            <span class="badge bg-success">Compliant</span>
                                        {% else %}
                                            <span class="badge bg-danger">Non-Compliant</span>
                                        {% endif %}
              
                                    {% elif "promo_flag" in column.name %}
                                      {% if data.promo_flag %}
                                        <span class="badge badge-sm bg-gradient-success">{{data.discount_percentage}}%</span>        
              
                                        {% else %}
                                        <span class="badge badge-sm bg-gradient-secondary">OFF</span>        
                                        {% endif %}
                
                                    {% elif "RSP" in column.name %}
                                        {{ data.product.RSP|floatformat:"2" }}
              
                                    {% elif "final_price" in column.name %}
                                        {{ data.product.final_price|floatformat:"2" }}
              
                                    {% elif "amazon_sold_by" in column.name %}
                                      {{ data.amazon_sold_by }}
              
                                    {% elif "noon_sa_sold_by" in column.name %}
                                      {{ data.noon_sa_sold_by }}
              
                                    {% elif "opps" in column.name %}
                                      {{ data.opps|floatformat:"2" }}
              
                                    {% elif "price_deviation_score" in column.name %}
                                      {{ data.price_deviation_score|floatformat:"2" }}                        
                                    {% elif "account_deviation_score" in column.name %}
                                      {{ data.account_deviation_score|floatformat:"2" }}                        
                                    {% endif %}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
          </div>
      </div>
      
      <div class="col p-4">
        <a href="{% url 'dashboard:toggle_pin_table' 'CurrentPriceStatus' %}" >
            {% if is_table_pinned %}
                Unpin Table
            {% else %}
                Pin Table
            {% endif %}
        </a>
      </div>

    </div>
  </div>
</div>


</div>



<!-- <script>
  document.addEventListener('DOMContentLoaded', function () {
    // Select all popover elements and initialize them
    var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
    var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
      return new bootstrap.Popover(popoverTriggerEl)
    })
  });
</script> -->





{% include "includes/footer.html" %}

{% endblock content %}

dashboard/templates/dashboard/product_performance.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load custom_filters %}

{% block content %} 


<div class="container-fluid">    

<div class="row my-4">
  <h1>Download Performance Data</h1>
  <p>Click the button below to download performance data in Excel format.</p>
  
</div>
<a href="{% url 'dashboard:download_performance_data' %}" class="btn btn-primary">Download Data</a>

</div>



<!-- <head>
    <meta charset="UTF-8">
    <title>Scraped Data List</title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.2.2/css/buttons.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
</head>

  <div class="row mt-3">    
    <div class="container mt-3">
      <h1>Performance View</h1>
    <div class="row">
        <div class="col-md-4">
            <input type="text" id="dateRange" class="form-control" placeholder="Filter by date range">
        </div>
    </div>
    <table id="PerformanceData" class="display">

      <thead>
      <tr>
        <th>Product Title</th>
        <th>Promo Flag</th>
        <th>Final Price</th>
        {% for column in columns %}
          {% if "_price" in column.name %}
            <th>{{ column.header }}</th>
          {% endif %}
        {% endfor %}

        {% if show_amazon_sold_by %}
        <th>Amazon Sold By</th>
        {% endif %}

        <th>Amazon Comp</th>
        <th>Dawa Comp</th>
        <th>Nahdi Comp</th>
        <th>ADS</th>
        <th>PCS</th>
        <th>PDS</th>
        <th>OPPS</th>
        <th>Update at</th>

      </tr>
    </thead>
    <tbody>
      {% for row in scraped_data %}
        <tr>
          <td>{{ row.product.TITLE }}</td>

          <td class="align-middle text-center text-sm">
            {% if row.promo_flag %}
            <span class="badge badge-sm bg-gradient-success">ON</span>        
            {% else %}
            <span class="badge badge-sm bg-gradient-secondary">OFF</span>        
            {% endif %}
          </td>


          <td>{{ row.final_price|floatformat:2 }}</td>
          {% for column in columns %}
            {% if "_price" in column.name %}
              <td>
                {# Get the corresponding compliance flag dynamically using the custom replace filter #}
                {% with compliance_flag=column.name|replace:"price,compliance_flag" %}
                  {% if row|get_item2:compliance_flag %}
                    <span class="badge bg-success">{{ row|get_item2:column.name|default_if_none:"N/A" }}</span>
                  {% else %}
                    <span class="badge bg-danger">{{ row|get_item2:column.name|default_if_none:"N/A" }}</span>
                  {% endif %}
                {% endwith %}
              </td>
            {% endif %}
          {% endfor %}



          {% if show_amazon_sold_by %}
          <td class="text-center">
              {% if row.amazon_sold_by != "Amazon.sa" %}
                  <span style="color: red;">{{ row.amazon_sold_by }}</span>
              {% else %}
                  {{ row.amazon_sold_by }}
              {% endif %}
          </td>
          {% endif %}

          <td>{{ row.amazon_compliance_score|floatformat:2|default:"N/A" }}</td>
          <td>{{ row.dawa_compliance_score|floatformat:2|default:"N/A" }}</td>
          <td>{{ row.nahdi_compliance_score|floatformat:2|default:"N/A" }}</td>
          <td>{{ row.account_deviation_score|floatformat:2 }}%</td>

      
          <td>{{ row.pcs|floatformat:2 }}%</td>
          <td>{{ row.price_deviation_score|floatformat:2 }}%</td>
          <td>{{ row.opps|floatformat:2 }}%</td>        
          <td>{{ row.scraped_at|date:"F j, Y, g:i a"  }}</td>

        </tr>
      {% endfor %}
    </tbody>
  </table>

</div>
  <div class="mt-3">
    <a href="{% url 'dashboard:toggle_pin_table' 'PerformanceData' %}">
        {% if is_table_pinned %}
            Unpin Table
        {% else %}
            Pin Table
        {% endif %}
    </a>
    </div>
</div>

<script>
  $(document).ready(function() {
      // Initialize DataTable with export buttons
      var table = $('#PerformanceData').DataTable({
          dom: 'Bfrtip',
          buttons: [
              'copyHtml5',
              'excelHtml5',
              'csvHtml5',
              'pdfHtml5'
          ]
      });

      // Initialize Date Range Picker
      $('#dateRange').daterangepicker({
          opens: 'left',
          autoUpdateInput: false,
          locale: {
              cancelLabel: 'Clear'
          }
      });

      // Apply the date range filter
      $('#dateRange').on('apply.daterangepicker', function(ev, picker) {
          $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
          $.fn.dataTable.ext.search.push(
              function(settings, data, dataIndex) {
                  var min = picker.startDate;
                  var max = picker.endDate;
                  var date = moment(data[4], 'MMMM D, YYYY, h:mm a'); // Assuming your date is in the 5th column (index 4)

                  if (min == null && max == null) {
                      return true;
                  }
                  if (min == null && date <= max) {
                      return true;
                  }
                  if (max == null && date >= min) {
                      return true;
                  }
                  if (date <= max && date >= min) {
                      return true;
                  }
                  return false;
              }
          );
          table.draw();
      });

      $('#dateRange').on('cancel.daterangepicker', function(ev, picker) {
          $(this).val('');
          $.fn.dataTable.ext.search.pop();
          table.draw();
      });
  });
</script> -->


{% endblock content %}